# Generated by Django 2.0.3 on 2019-01-21 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('small', 'small'), ('large', 'large'), ('none', 'none')], default='none', max_length=9)),
                ('toppings_class', models.CharField(default='None', max_length=9)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=14)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('items', models.ManyToManyField(to='orders.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(choices=[('pepperoni', 'pepperoni'), ('sausage', 'sausage'), ('mushrooms', 'mushrooms'), ('onions', 'onions'), ('ham', 'ham'), ('canadian bacon', 'canadian bacon'), ('pineapple', 'pineapple'), ('eggplant', 'eggplant'), ('tomato & basil', 'tomato & basil'), ('green_peppers', 'green_peppers'), ('hamburger', 'hamburger'), ('spinach', 'spinach'), ('artichoke', 'artichoke'), ('buffalo chicken', 'buffalo chicken'), ('anchovies', 'anchovies'), ('black olives', 'black olives'), ('fresh garlic', 'fresh garlic'), ('zuchinni', 'zuchinni')], default=None, max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='toppings',
            field=models.ManyToManyField(to='orders.Toppings'),
        ),
    ]
