# Generated by Django 2.0.3 on 2019-01-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190121_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
